# Generated by Django 2.1.3 on 2018-11-08 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='meetup_going',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.MeetUps'),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='user_going',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='going_to', to='events.Users'),
        ),
    ]
