# Generated by Django 2.1.3 on 2018-11-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181107_2340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendees',
            unique_together={('meetup_going', 'user_going')},
        ),
    ]
